### ISSUE TITLE
Prvotny nastrel zoznamu poziadaviek

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#1]
Do utorka 16.10. poslat zadavatelovi uceleny nastrel zoznamu poziadaviek (nie este vysledny Katalog, na ten bude hned v navaznosti vytvorena nova issue) na pripadnu iteraciu. Pri tvorbe vychadzat zo zaznamu zo stretnutia (v branch docs) a videi z prezentacie.

**Comment by senkovicova1** [comment]
Prvotny nastrel som dnes poslala p. Vargovi a poprosila ho o cim skorsie vyjadrenie.

**Comment by pavelpetrovic** [comment]
dufam, ze ho ziadna gulka nezasiahne.
