### ISSUE TITLE
Vyzdvihnúť pomôcky na projekt u p. Vdoviaka

### ISSUE THREAD

**Issue by senkovicova1** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#14]
Dnes som po ne išla. Máme stojan, lanko, niekoľko závaží rôznych veľkostí a váh. K tomu máme dve externé  kamery, ktoré si treba rozdeliť. Ja mám svoju, takže pri deľbe práce na SW sa zrejme dohodneme, ktorí dvaja z kolegov ich dostanú.

**Comment by jurovee** [comment]
poprosim si

**Comment by senkovicova1** [comment]
Oki, stačí ti ju doniesť po prázdninách, či ju potrebuješ už na ďalší týždeň?

**Comment by jurovee** [comment]
po staci
