### ISSUE TITLE
UML state diagram

### ISSUE THREAD

**Issue by Jozkings** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#15]
Nakresliť a prediskutovať s kolegami/p. Petrovičom

**Comment by Jozkings** [comment]
![state_diagram1](https://user-images.githubusercontent.com/36714542/47966397-222b4000-e052-11e8-82dd-05f7e1649225.png)
Prvotný návrh, prosím skontrolovať iným členom

**Comment by Jozkings** [comment]
![state_diagram2](https://user-images.githubusercontent.com/36714542/48319853-3ef7e280-e613-11e8-81f6-8bf8a312a228.png)

Návrh č.2, po úpravách, poprosím o kontrolu

**Comment by Jozkings** [comment]
![state_diagram3](https://user-images.githubusercontent.com/36714542/48662134-c1522d80-ea7d-11e8-993e-25f5f5e0e4e8.png)

Návrh č.3, žiadam o kontrolu

**Comment by Jozkings** [comment]
[state_diagram_popis.pdf](https://github.com/TIS2018-FMFI/visionlab-fyzikalne-experimenty/files/2595486/state_diagram_popis.pdf)

Popis state diagramov, doplniť do návrhu

**Comment by jurovee** [comment]
Uz neboli viacmenej pripomienky, davam close. Final verzia je v navrh_in_progress.pdf.

**Comment by jurovee** [comment]
:(

**Comment by Jozkings** [comment]
![state_diagram_final](https://user-images.githubusercontent.com/36714542/49017234-a623a400-f188-11e8-8b89-14beaa88e84f.png)

Konečná verzia, zakomponovať do návrhu
