### ISSUE TITLE
Vyskúšať dodanú triedu pre vykresľovanie 

### ISSUE THREAD

**Issue by Jozkings** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#18]

**Comment by Jozkings** [comment]
S triedou sú menšie komplikácie a nefunguje zatiaľ správne, takže sa dnes skúsime na stretnutí pozrieť na problém bližšie a prípadne počkať na odpoveď od p. Solčániho, aby do pondelka bola trieda odskúšaná a vedeli ju všetci použiť

**Comment by Jozkings** [comment]
Triedu sa konečne podarilo spustiť, ale po viacerých úpravách. Bolo potreba staršiu verziu openCV (z 4.0.0 -> 2.4.9) V tomto prípade sa po veľkom snažení trieda spustí, ale len v release mode ( čo treba zase ručne pomeniť v kóde a nastaveniach Visual Studia).  Na použitie Debug modu by bolo treba mať nainštalovaný Visual Studio 2013. Podľa varovanie p. Solčániho, obrázok sa vykreslí len v Debug móde, a nie v Release, avšak spustenie programu potvrdzuje, že sa triedu naozaj podarilo spustiť. Samotný proces je však natoľko obtiažny, že bude treba vytvoriť dokument s podrobným návodom.

**Comment by pavelpetrovic** [comment]
pozrite si aj tento priklad prosim (na konci diskusie v issue):

https://github.com/TIS2018-FMFI/visionlab-meraky/issues/7#issuecomment-441007059
