### ISSUE TITLE
Preskúmanie výpočtu veličín vykresľovaných v grafe

### ISSUE THREAD

**Issue by senkovicova1** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#24]
Zistiť ako presne (a či) sa dajú vypočítať veličiny, kt. budú ukazované v grafe.

**Comment by senkovicova1** [comment]
Mala som problém nájsť vzorec na výpočet maximálnej výchylky, resp. čo to je pri fyzikálnom kyvadle -zrejme vyriešime zajtra. Ostatné vzorce som našla a spísala - budem ich ale ešte overovať, keďže som častokrát našla rôzne vzorce na jednu veličinu a niekedy si protirečia.

Zopár linkov z kt. som čerpala a pripadali mi, že by sa ešte mohli hodiť:
https://www.youtube.com/watch?v=KFobCLTtXAg a https://www.physicsforums.com/threads/pendulum-velocity-at-any-given-angle.737577/
https://www.physicsforums.com/threads/angular-velocity-of-a-simple-pendulum.954047/
https://www.physicsforums.com/threads/angular-acceleration-of-pendulum-equation.885926/
https://www.physicsforums.com/threads/angular-velocity-pendulums-and-ideal-springs.287205/
http://www.uq.edu.au/_School_Science_Lessons/UNPh15.html

**Comment by senkovicova1** [comment]
Vyriešili sme výpočet maximálnej výchylky. Už len treba skontrolovať správnosť vzorcov.

**Comment by jurovee** [comment]
@senkovicova1 asi finito ci?

**Comment by senkovicova1** [comment]
Spísala som vzorce do súboru a poslala Jurkovi na zapracovanie do návrhu.
