### ISSUE TITLE
Domyslieť vykreslovanie grafu

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#25]
https://www.codeproject.com/Articles/14075/High-speed-Charting-Control

**Comment by jurovee** [comment]
https://www.gigasoft.com/mfcchartinglibrary.html

**Comment by senkovicova1** [comment]
Pozrela som obe možnosti a druhú som už aj vyskúšala. Projekt s ňou išiel spustiť relatívne rýchlo a s grafom sa dá dobre narábať pri behu aplikácie - napr, dajú sa meniť spôsoby vykresľovania grafu (čiary, body, krivky, bars...). Viac o tom poviem zajtra na stretnutí.
