### ISSUE TITLE
Naprogramovať triedu Dataset

### ISSUE THREAD

**Issue by Jozkings** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#29]
V triede budú uložené všetky záznamy z merania, t.j. časové body a jednotlivé hodnoty veličín s ich výpočtami.

**Comment by Jozkings** [comment]
[DataSet.zip](https://github.com/TIS2018-FMFI/visionlab-fyzikalne-experimenty/files/2729898/DataSet.zip)
Trieda DataSet spolu s testami. Jej správnosť a úplnosť ešte dodatočne preveríme v skúške s ostatnými modulami programu

**Comment by pavelpetrovic** [comment]
na github sa nikdy nekomituju zdrojaky v zip-e.
na to je to git, ze archivuje zdrojove subory a nie zip-subory.
v gite si vytvorte adresarovu strukturu, kde budete zdrojaky umiestnovat a nahrajte to tam.
samozrejme vo svojej branchi, ktoru treba cez pull request potom ako to niekto iny skontroluje, pochopi a pripadne napise pripomienky, ktore sa este v dalsich commit-och zohladnia, cize potom ako na to niekto urobi approving review, az potom sa to zmerguje do mastra.

**Comment by Jozkings** [comment]
Rozumiem, ďakujem za pripomienku.

**Comment by Jozkings** [comment]
Po dodatočnom preskúmaní som zistil, že ešte treba jemne upraviť triedu(ukladanie času). Toto bude pridané zajtra do môjho brancha a následne sa trieda posúdi na stretnutí a prípadné zmeny opíšem tu.

**Comment by Jozkings** [comment]
Naprogramovaný Dataset aj s väzbami na exporty a graf
