### ISSUE TITLE
Pridat zadavatelov do repozitara

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#3]
Zistit githubove accounty p. Vargu a p. Solcaniho a pridat ich sem na prezeranie.

**Comment by senkovicova1** [comment]
Tu su ich ucty: 
kv32varga
kv32solcani
Ja ich ale ako kontributorov pridat neviem. Resp. nemam Settings okienko, kde sa to da.

**Comment by jurovee** [comment]
@pavelpetrovic viete nam s tym pomoct prosim? Vdaka

**Comment by pavelpetrovic** [comment]
nie som si isty, ci ich zatial cheme pridavat do repozitara.
ked to bude potrebne, tak ich pridame.
pisal som medzitym panovi Vargovi o rezime prace, takze sa pocas vyvoja nebudu musiet zatazovat sledovanim vasho projektu. pripadne sa s nimi este priebezne dohodnem.
