### ISSUE TITLE
Naprogramovať GUI aplikácie

### ISSUE THREAD

**Issue by Jozkings** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#31]

**Comment by senkovicova1** [comment]
Je v branchi "sonka-vyklikane-GUI". Samozrejme, este treba doprogramovat funkcionalitu. Zatial buttony schovaju/zobrazia prvky, ktorych sa tykaju.

**Comment by jurovee** [comment]
GUI je naprogramovane + pozmenene na zaklade postrehov zadavatela.
pripadne upravy su este mozne (config kamery)
