### ISSUE TITLE
Spísanie testovacích scenárov

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#32]

**Comment by jurovee** [comment]
zakladne scenare su uz davnejsie spravene, poprosim ta @senkovicova1 velmi pekne ku kapustnici este preliezt ocami ten dokument, ci som pokryl vsetky poziadavky v KP. Dakujeeeem.

@Jozkings @Zortox1 @senkovicova1 nezabudnite pri programovani mysliet na testovanie vasho kodu, t.j. vymyslat si vhodne unit testy, niekde si to udrziavajte a potom mi poslite na zapracovanie do TS. Thanks, Merry Christmas.

**Comment by senkovicova1** [comment]
Pri TS 2.3 a TS 2.4 trochu nerozumiem alternatívnym scenárom, konkrétne bodu 2 v postupe. 
Tj ''V zobrazenom okne nie je prítomný zoznam radiobuttonov pre 
nastavenie rozlíšenia'' a ''V zobrazenom okne nie je prítomný horizontálny scrollbar pre nastavenie expozície.'' 
Je to pre prípady, kedy sa rozlíšenie a expozícia nedá nastaviť alebo keď si user rozmyslí zmenu? Prípadne, nebolo by tam lepšie aj pridať mini-case, kedy user stlačí tlačidlo nastavenia kamery, ale nič neurobí? 
Inak myslím, že si obsihaol všetko, minimálne mi nič viac nenapadá.

**Comment by jurovee** [comment]
upravim, dobre postrehy.

--upravene
