### ISSUE TITLE
Doprogramovať do aplikácie export PDF

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#33]

**Comment by Jozkings** [comment]
Na export bude nakoniec použitá knižnica PDF Creator Pilot- Demo. Ostatné C++ knižnice(vrátane pôvodne plánovaného libharu) sa nedajú správne nainštalovať do najnovšej verzie Visual Studio 2017(väčšina z nich je totižto už dosť stará)

**Comment by Jozkings** [comment]
Export hotový, pripravený do finálnej verzie
