### ISSUE TITLE
Ako spojiť naše časti?

### ISSUE THREAD

**Issue by senkovicova1** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#35]
Na stretnutí sme sa bavili o tom, že potrebujeme prepojiť obraz z kamery s grafom a so zvyškom aplikácie. Problém je, že výsledná aplikácia má byť dialog based, no graf je v mdi a nevieme ho prepojiť. Neviem, ako je na tom OpenCV časť.
Keď sa toto vyrieši, budú stačiť už len drobné úpravy kódu.

**Comment by senkovicova1** [comment]
Nejaké články, ktoré som vygooglila a zdali sa byť k veci:
https://www.codeguru.com/cpp/w-d/dislog/miscellaneous/article.php/c2013/Dialog-which-can-be-used-as-MDI-child-window.htm (z roku 1998...)
https://www.codeproject.com/Articles/721/%2FArticles%2F721%2FCreating-your-first-MFC-Doc-View-application
https://social.msdn.microsoft.com/Forums/vstudio/en-US/1370455b-899b-4056-b3ec-66f31bc74f55/how-to-create-an-mfc-mdi-child-window-using-a-dialog-template-not-a-docview-approach-modeless?forum=vcgeneral
https://www.codeproject.com/Articles/48436/%2FArticles%2F48436%2FMDI-child-as-dialog-form-MDI-modal-workaround

Postup + triedy, o kt. som dnes hovorila na stretnutí a v branchi sonka-MDI-in-Dialog-Based-App je môj poku so replikáciu: https://www.codeproject.com/Articles/1369/%2FArticles%2F1369%2FInserting-a-Doc-Frame-View-in-a-dialog-using-a-cus

Možno najužitočnejšie? VC++ MFC Basics - 5 - Dialog box with SDI - https://www.youtube.com/watch?v=bZkB1TAg5tc 

Info o tom, čo je vlastne MFC document view https://www.tutorialspoint.com/mfc/mfc_document_view.htm

**Comment by senkovicova1** [comment]
Nie presne čo chceme, ale možno pomôže: 

https://www.youtube.com/watch?v=yr8-qQGg3Gs

Pt1: https://www.youtube.com/watch?v=tfl4I41YiFg
Pt2: https://www.youtube.com/watch?v=xSevTT_Y1yw 

Trochu nie to, čo hľadáme, ale aspoň ukazuje, ako previazať views: https://www.youtube.com/watch?v=Vp81ypJAyVs

**Comment by jurovee** [comment]
je to spojene uz dlhsie, uz su len dorabky detailov, dovolim si close
