### ISSUE TITLE
Skompletizovať katalóg požiadaviek a odoslať zadávateľovi

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#4]
Dokončiť niektoré kapitoly a doplniť už zadávateľom schválené požiadavky do výsledného katalógu požiadaviek.

**Comment by jurovee** [comment]
tato issue ma na mysli vysledny katalog na review, ak nebudu vyhrady zo strany zadavatela tak close toto aj #6

**Comment by pavelpetrovic** [comment]
- KP nie je urceny IBA pre zadavatela
- pomocou aplikacii PV ??
- matematickú reprezentáciu konkrétnych vlastností objektu ?
- 2.2 Pre presnosť výpočtov?
- základná znalosť o samotnom kyvadle?
- 3.2.9. správnosti vykreslovania niektorých údajov ?
- 3.2.10.2 doplnit skalovanie casu
- v predpokladoch
   - co sa v scene moze pohybovat
   - farba je kontrastna oproti pozadiu
- doriesit kalibraciu:
     - farebny interval pre zlozky H,S modelu HSV - idealne v konfiguracnom subore
     - pixel per cm 
 - o exportoch pisat blizko
   bud PDF alebo CSV
- moznost nastavit dlzku zavesu kyvadla
- do poziadaviek pridat, ze k aplikacii bude prilozeny strucny navod na pouzitie

**Comment by senkovicova1** [comment]
Upraveny katalog som poslala p.Petrovicovi, ak bude ok, poslem ho aj zadavatelom na schvalenie a closenem tento issue

**Comment by senkovicova1** [comment]
Katalog bol upraveny podla dalsich pripomienok a odoslany zadavatelom.
