### ISSUE TITLE
Odoslanie finálneho katálogu požiadaviek zadávateľovi

### ISSUE THREAD

**Issue by jurovee** [TIS2018-FMFI/visionlab-fyzikalne-experimenty#6]
@senkovicova1 poprosim o close ked sa to stane realitou

**Comment by senkovicova1** [comment]
Zadávateľom som odoslala ešte nie finálny katalóg požiadaviek a čakám na ich odpoveď, podľa ktorej katalóg upravíme.

**Comment by senkovicova1** [comment]
Upravila som katalóg podľa návrhov p. Vargu a poslala im ho na odobrenie.
